doctrine:
    dbal:
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
        default_connection: default
        connections:
            default:
                driver: 'pdo_pgsql'
                server_version: '16'
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types: {uuid: uuid}
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Questionnaire:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Questionnaire/Infrastructure/Doctrine/Mapping'
                prefix: 'Questionnaire\Domain\Entity'
                alias: Questionnaire
