framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
        transports:
            sync: 'sync://'

        routing:
            'Questionnaire\Application\Query\GetQuestionnaire\GetQuestionnaireQuery': sync
            'Questionnaire\Application\Query\GetUserQuestionnaire\GetUserQuestionnaireQuery': sync
