version: '3.5'

services:
  nginx:
    ports:
      - "8181:80"
    image: nginx:stable-alpine
    networks:
      - task
    volumes:
      - ./public:/var/www/app/public
      - ./docker/app/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: docker/app/php
      args:
        BUILD_ENV: ${BUILD_ENV:-dev}
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USERNAME: ${USERNAME:-www-data}
    tty: true
    depends_on:
      - nginx
      - postgres
    networks:
      - task
    volumes:
      - ./:/var/www/app
      - ./docker/app/php/php-ini-extra.ini:/usr/local/etc/php/conf.d/docker-php-ext-php-ini-extra.ini
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5435:5432"
    networks:
      - task
    volumes:
      - postgres:/var/lib/postgresql

networks:
  task: ~

volumes:
  postgres: { }
